### ISSUE TITLE
구글 스프레드 시트 및 참고할 링크

### ISSUE THREAD

**Issue by Joto-Han** [5kiran/94DOG#3]
다이어그램
https://drive.google.com/file/d/1zlvBPZsEavt9KHOH5coWYd88BR3_z3b-/view?usp=sharing

스프레드시트
https://docs.google.com/spreadsheets/d/1Gq-sI0xdlR5qkEkw5m9KFNEM67E4yppwheKZjSEFMpE/edit#gid=0

**Comment by cchoseonghun** [comment]
테스트 이슈이므로 close
